### ISSUE TITLE
App crashes when downloading video

### ISSUE THREAD

**Issue by akhimnt** [SongTube/SongTube-App#10]
I cloned the repository. When I run the App, it crashes just before the downloaded video and audio patches.

**Comment by akhimnt** [comment]
This is the error `I/flutter ( 3667):     Metadata:
I/flutter ( 3667):       creation_time   :
I/flutter ( 3667): 2020-07-18T09:29:03.000000Z
I/flutter ( 3667):
I/flutter ( 3667):       handler_name    :
I/flutter ( 3667): ISO Media file produced by Google Inc.
I/flutter ( 3667):
E/AndroidRuntime( 3667): FATAL EXCEPTION: AsyncTask #7
E/AndroidRuntime( 3667): Process: com.artxdev.songtube.dev, PID: 3667
E/AndroidRuntime( 3667): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 3667): 	at android.os.AsyncTask$3.done(AsyncTask.java:354)
E/AndroidRuntime( 3667): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 3667): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 3667): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 3667): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime( 3667): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 3667): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 3667): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime( 3667): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.List.toArray(java.lang.Object[])' on a null object reference
E/AndroidRuntime( 3667): 	at com.arthenica.flutter.ffmpeg.FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.doInBackground(FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.java:52)
E/AndroidRuntime( 3667): 	at com.arthenica.flutter.ffmpeg.FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.doInBackground(FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.java:38)
E/AndroidRuntime( 3667): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime( 3667): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 3667): 	... 4 more
I/Process ( 3667): Sending signal. PID: 3667 SIG: 9
Lost connection to device.
Exited (sigterm)

`

**Comment by Artx-II** [comment]
> This is the error `I/flutter ( 3667): Metadata:
> I/flutter ( 3667): creation_time :
> I/flutter ( 3667): 2020-07-18T09:29:03.000000Z
> I/flutter ( 3667):
> I/flutter ( 3667): handler_name :
> I/flutter ( 3667): ISO Media file produced by Google Inc.
> I/flutter ( 3667):
> E/AndroidRuntime( 3667): FATAL EXCEPTION: AsyncTask #7
> E/AndroidRuntime( 3667): Process: com.artxdev.songtube.dev, PID: 3667
> E/AndroidRuntime( 3667): java.lang.RuntimeException: An error occurred while executing doInBackground()
> E/AndroidRuntime( 3667): at android.os.AsyncTask$3.done(AsyncTask.java:354)
> E/AndroidRuntime( 3667): at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
> E/AndroidRuntime( 3667): at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
> E/AndroidRuntime( 3667): at java.util.concurrent.FutureTask.run(FutureTask.java:271)
> E/AndroidRuntime( 3667): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
> E/AndroidRuntime( 3667): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> E/AndroidRuntime( 3667): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> E/AndroidRuntime( 3667): at java.lang.Thread.run(Thread.java:764)
> E/AndroidRuntime( 3667): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.List.toArray(java.lang.Object[])' on a null object reference
> E/AndroidRuntime( 3667): at com.arthenica.flutter.ffmpeg.FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.doInBackground(FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.java:52)
> E/AndroidRuntime( 3667): at com.arthenica.flutter.ffmpeg.FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.doInBackground(FlutterFFmpegExecuteFFmpegAsyncArgumentsTask.java:38)
> E/AndroidRuntime( 3667): at android.os.AsyncTask$2.call(AsyncTask.java:333)
> E/AndroidRuntime( 3667): at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> E/AndroidRuntime( 3667): ... 4 more
> I/Process ( 3667): Sending signal. PID: 3667 SIG: 9
> Lost connection to device.
> Exited (sigterm)
> 
> `

Can you share the video link that causes this issue and which download option you selected?

**Comment by akhimnt** [comment]
It happens on every video, audio download is working perfectly. When I download any video app crashes. I just uploaded a screen record of the app crash. and also there is another problem ie: Downloading process is not continuous, it pauses for 2 or 3 sec every few seconds. and the download speed is very low. you can see it in the video.
[Screenrecorder-2020-11-15-06-18-35-859.zip](https://github.com/SongTube/SongTube-App/files/5541665/Screenrecorder-2020-11-15-06-18-35-859.zip)
