### ISSUE TITLE
[Feature Request] Add sponsor blocking implementation

### ISSUE THREAD

**Issue by AnonyUnknownTg** [SongTube/SongTube-App#103]
There's a project using a crowd-sourced tagging database to skip over parts of the video dedicated to sponsorship and advertisements.

Take a look [here](https://github.com/ajayyy/SponsorBlock) !

I think it could be a helpful feature to integrate.

**Comment by Artx-II** [comment]
Healthy methods of sponsorship for contents creators to earn revenue from their work is not going to be blocked on this app.
