### ISSUE TITLE
Video player 720p > 480p

### ISSUE THREAD

**Issue by VstMusic-SoloStudio** [SongTube/SongTube-App#110]
It can be preset with 480p instead of 720p so that the videos can be played faster outside of wifi and to be quota friendly.

**Comment by AnonyUnknownTg** [comment]
And an option regarding the same would be great.

**Comment by Artx-II** [comment]
720p should be the base minimum these days for watching videos at a reasonable quality, and if the user wants lower he can just we it to 480p and future videos loaded will by default load on 480p.

In the future I can implement a network speed based quality switcher and also a mobile data saver, but this is just tons of work at the moment (and this should have its own issue)
