### ISSUE TITLE
[Home Page] UI improvement (Make checkboxes rounded)

### ISSUE THREAD

**Issue by AnonyUnknownTg** [SongTube/SongTube-App#112]
![IMG_20211001_164322_887](https://user-images.githubusercontent.com/87353286/135611628-47faea45-4ab4-4b55-99ac-3573ca8643b9.jpg)

Those checkboxes could have rounded corners.

**Comment by Artx-II** [comment]
Boiler plate code I want to avoid, maybe a re-design could be done later to that bottom panel
