### ISSUE TITLE
[UI] Video Page (Empty area until everything loads)

### ISSUE THREAD

**Issue by vedxp** [SongTube/SongTube-App#117]
![IMG_20211003_120541_635](https://user-images.githubusercontent.com/87353286/135742946-71de1106-33fc-420a-bb4b-3c6b63d39662.jpg)

There's an empty gap between Video Title and Channel Bar, until other stuffs load.

Instead, make the Channel Bar lazy load with other stuffs; so that everything loads at the same time with no UI emptyness until others load.

**Comment by AnonyUnknownTg** [comment]
![Screenshot_20211004-071243_SongTube](https://user-images.githubusercontent.com/87353286/135786953-e0aacb1c-24c5-4be4-b765-5f92b45d8408.png)

Lazy load that subscribe button too.

**Comment by Artx-II** [comment]
Updated repo with the new project. It works now.
