### ISSUE TITLE
[Video Player] Missing smoothness (Volume Slider)

### ISSUE THREAD

**Issue by vedxp** [SongTube/SongTube-App#118]
- Play any video
- Enter fullscreen
- Swipe left side, brightness value text changes correctly, with no gap b/w values
- Swipe right side, volume value text goes from 0 to 37 to 49 and vice-versa
- Volume slider isn't consistent and smooth

**Comment by ishanvaghani** [comment]
PR is raised for this fix - [Link](https://github.com/SongTube/SongTube-App/pull/257)
@Artx-II can you check the PR?

**Comment by Artx-II** [comment]
Fixed by commit 5ad7adf
