### ISSUE TITLE
[Feature Request] Can it be downgraded to Android 5.0.1(api 21)?

### ISSUE THREAD

**Issue by dickyharper** [SongTube/SongTube-App#12]
I saw the Songtube app on another phone.  But unfortunately it doesn't support my phone.  My phone is 5.0.1, I know it's old.  Currently the minimum api for the app is 22. Can Api 21 be supported? 
Thanks.

**Comment by enweazudaniel** [comment]
If you're sure your phone is lollipop 5.0 then it should work because it meets the minimum requirement

**Comment by dickyharper** [comment]
> 
> 
> Unfortunately 21 API cannot be supported because the framework flutter support minimum 22 API. if you are satisfied with this answer kindly close this issue thanks.
> With love from #SongtubeTeam ❤️

I understand, thanks for your reply.
