### ISSUE TITLE
[Search] Bug (White tint until suggestions load)

### ISSUE THREAD

**Issue by AnonyUnknownTg** [SongTube/SongTube-App#122]
![Screenshot_20211004-081844_SongTube](https://user-images.githubusercontent.com/87353286/135786427-413fb45c-8a76-4e75-b315-0a5fa43a8368.png)

https://user-images.githubusercontent.com/87353286/135786488-f93ab85b-8002-45d4-8aea-9b9aaad6c112.mp4

**Comment by Artx-II** [comment]
Great observation, this was happening because symbols like # or & cannot be put onto a http query, for this reason the search suggestions were crashing and showing a grey background.

This has been fixed, thanks!
