### ISSUE TITLE
Keep order in audio tracks for `Segmented Download`

### ISSUE THREAD

**Issue by rlsgitmas** [SongTube/SongTube-App#129]
It would be great if the order of segmented audio tracks could be preserved when downloading audio.

Currently the application is very good at labeling different tracks but the order is not kept in the audio file - it is not fun to listen to electronic music out of order. 

It good be helpful to have the option to add the number of the audio track to the name, according to the order it was downloaded. Example below:

```
1. Track name 
2. Track name 
3. Track name 
```

**Comment by rlsgitmas** [comment]
Below is a screenshot of segmented downloads without order.

![downloads_without_number](https://user-images.githubusercontent.com/92409568/145912720-50948e9e-2992-436c-807a-31f203f5ea0e.png)\


Below is a screenshot of segmented download with order numbers but ordering of tracks restarts after Track # 33 - start to get tracks with duplicate track # (e.g.  01. Track, 01. Track.)

![segmented_with_numbers_but_restarts](https://user-images.githubusercontent.com/92409568/145912773-75cf6873-00a2-4871-882f-b6c38d83bb85.png)

**Comment by Artx-II** [comment]
A new feature to create a music playlist after downloading with audio segmentation has been added. This might help your case.

As for the order numbers restarting at 33, I was not able to reproduce this issue.
