### ISSUE TITLE
Typos in disclaimer.dart

### ISSUE THREAD

**Issue by Suvradippaul** [SongTube/SongTube-App#130]
### Two minor typos in [disclaimer.dart](https://github.com/SongTube/SongTube-App/blob/development/lib/ui/sheets/disclaimer.dart) need to be fixed.

1. [responsability](https://github.com/SongTube/SongTube-App/blame/development/lib/ui/sheets/disclaimer.dart#L11) > responsibility

2. [indidental](https://github.com/SongTube/SongTube-App/blame/development/lib/ui/sheets/disclaimer.dart#L13) > incidental

![spelling_mistake](https://user-images.githubusercontent.com/68487263/137638717-2267792a-7751-406b-8b74-8146d80afadc.jpg)

Am I allowed to make a PR with the above suggested changes? 
Thank You

**Comment by Artx-II** [comment]
Thank you, typos are fixed
