### ISSUE TITLE
Several Improvements

### ISSUE THREAD

**Issue by Quantenzitrone** [SongTube/SongTube-App#133]
IDK what the purpose of this app is, but guessing from the Name and some features, it seems to me to be Music-centered.
As by now, SongTube doesn't really differ from NewPipe, except a bit different (and damn beautiful) UI and a Music Tab.
- Play Videos as Audio only and make it default. Move the Play as Video feature in the context menu (three dots).
  - Maybe a setting for that.
  - Play videos in collapsed mode by default.
- Merge playlists in "Library" and "Music".
  - Local files should still be addable.
  - Create an easier accessible download button for playlists.
    - online videos (as in library playlists) should be considered the same as the downloaded files.
      - to identify them, the "Internet address" or the "Comments" tag for m4a files could maybe be used.
      - when playing an already downloaded video, the local file should be played automatically.
- Make video thumbnail as downloaded song album art.
  - For that to not mess up, I would suppose to make the video title as default album Instead of "YouTube".

Other UI Improvements:
- Open the context menu when long clicking on a video.
- Create "next" and "previous" button when playing from a playlist.
- Change the subscribe button text to unsubscribe when subscribed.
  - or to unsubscribed and subscribed.
- Setting for which folders should be scanned for audio files.
  - I have got a lot of non-music audio files in the "Songs" tab of the "Music" tab.

And some UI fixes:
- Add missing buttons for videos in the playing queue.
- Enlarge hitbox of video progress bar. It is really hard to hit.
- " * - Topic" Channels don't load and when subscribing to them prevent loading of Subscriptions Feed.

**Comment by Artx-II** [comment]
Repository was updated with the new project.

Thank you for the suggestions, some in this issue have been implemented. While the app focus is on music, the experience while watching a video is made to be close to the original Youtube app.

There are settings to change this default behavior of the video player, and more, coming soon.
