### ISSUE TITLE
Option to reorder pages at bottom.

### ISSUE THREAD

**Issue by kalkioss** [SongTube/SongTube-App#140]
I don't use trending page much, so, it would be great to set subscriptions page as first and default while opening. And it will be even better if the user can remove a page or tab (for me it's home page, that I want to hide😅).
And thank you so much for creating this wonderful project!

**Comment by Artx-II** [comment]
Repository was updated with the new project. There should be no need to reorder pages at the bottom with the new design. The app now offers default pages at the settings section.
