### ISSUE TITLE
Can not download files on Android 11

### ISSUE THREAD

**Issue by vankhoa01** [SongTube/SongTube-App#141]
Hi team, 
Thank you for creating this amazing app.
On Android 11 and newer, I can not download files. 
I know you had TEMP fix in Setting.

<img width="319" alt="Screen Shot 2021-12-19 at 20 47 16" src="https://user-images.githubusercontent.com/8953129/146677286-d1cbcd12-4c49-4f29-b404-6c11d789d8ad.png">

But as you know, Google is quite strict with MANAGE_EXTERNAL_STORAGE permission now.
So did you have any solution to resolve this issue ?

**Comment by demi-code** [comment]
I can confirm that this hasn't been solved yet. It mentions a step to fix this issue in-app but the solution doesn't seem to work.

**Comment by Artx-II** [comment]
Repository was updated with the new project. Fixed by now.
