### ISSUE TITLE
Album Cover is not always shown for OPUS (OGG) files

### ISSUE THREAD

**Issue by EmanuelLoos** [SongTube/SongTube-App#144]
For albums with multiple soundtracks having the audio coded in OPUS and the (large) album cover coded as MJPEG (Motion JPEG) stored in an OGG container along with some metadata the album cover is not always shown on the "Now Playing" view and sometimes in the "Albums Overview".

The albums where downloaded from YouTube (Music) using youtube-dl. The album cover was downladed by opening the image shown on YouTube Music in a new tab in the webbrowser changing the height and width parameters of the URL to get the largest version. It was embedded using Kid3.

**Comment by EmanuelLoos** [comment]
Fixed in the new version.

**Comment by Artx-II** [comment]
I don't recall fixing this, try testing again and make sure it's really fixed, otherwise re-open the issue and once I get the time, I will look into this.
