### ISSUE TITLE
[Feature Request] Option to customize content of bottom navigation bar

### ISSUE THREAD

**Issue by laraib07** [SongTube/SongTube-App#152]
Please provide a way to customize UI and disable some component for distraction free experience. One of reasons of choosing alternatives to Youtube app is to get rid of its addictive features. Maybe a approach similar to newpipe will work just fine. In newpipe we can choose content of main page. 

Screenshot from newpipe :
![dee6799d-9e8a-405c-8459-9fea35219ca0](https://user-images.githubusercontent.com/25507825/154246281-26e91662-8c4d-4f7e-97f6-12521208ecce.png)

**Comment by Artx-II** [comment]
Repository was updated with the new project. There is no need for this with the new design. Also, in the settings section you can change default pages for the app screens.
