### ISSUE TITLE
Bug : Clear the download queue after switching between applications

### ISSUE THREAD

**Issue by Mahantor** [SongTube/SongTube-App#155]
I have added some videos to the download queue and after moving or closing the program and reopening it, I will encounter an empty download queue

**Comment by Clashkid155** [comment]
It's not a bug. For now the downloading aren't saved.

Don't close the app till your download is done. Hopefully this will be added soon.

**Comment by Artx-II** [comment]
This will be added soon in the form of a download service. But it makes things a bit more complicated so it will come later, on a new issue.
