### ISSUE TITLE
Cover art does not download properly when downloading a playlist

### ISSUE THREAD

**Issue by Snelso91** [SongTube/SongTube-App#157]
When downloading a whole Youtube Music playlist as audio, the cover art for the songs does not download properly. However, if the same songs from the playlist are individually downloaded as audio, then the cover art is properly downloaded.

Example test playlist [link](https://music.youtube.com/playlist?list=PL0d1q46w5FMFvIfaiNQFgJ-MXM6LoCZAc)
Whole playlist downloaded as audio tracks:
![Whole playlist downloaded as audio tracks](https://user-images.githubusercontent.com/78712321/154942961-9ab00917-9502-48cb-ad63-c317539659eb.png)
Individually downloaded audio tracks:
![Individually downloaded audio tracks](https://user-images.githubusercontent.com/78712321/154943044-432d5531-142b-4ff7-8bb2-5b61e1d5d931.png)

**Comment by Artx-II** [comment]
Repository was updated with the new project. Downloading a whole playlist is not yet re-implemented.

Another issue will be made to address this.
