### ISSUE TITLE
Certain YouTube Music playlists will not download properly

### ISSUE THREAD

**Issue by Snelso91** [SongTube/SongTube-App#158]
When downloading [this playlist](https://music.youtube.com/playlist?list=PL0d1q46w5FMH4bvevZpyUIplCykGOdOX9), SongTube gets stuck on the second song (Scars) which will remain in the downloads queue forever until the app is closed, but it downloads the other 3 songs without issues.
If I put the exact same 4 songs in the same order in a [brand new playlist](https://music.youtube.com/playlist?list=PL0d1q46w5FMFvIfaiNQFgJ-MXM6LoCZAc), the whole playlist downloads without issue.
Given that I can play the whole of either playlist in YouTube Music with no problems, and they both display all the songs and in the correct order, I'm not sure why SongTube is having issues with the original older playlist vs the newly created playlist?

**Comment by Artx-II** [comment]
Repository was updated with the new project. Downloading a playlist is not yet re-implemented.

Another issue will be made to address this.
