### ISSUE TITLE
[Feature Request] Update tags when media get downloaded

### ISSUE THREAD

**Issue by bohrasankalp** [SongTube/SongTube-App#16]
We have feature to add audio tags, before media gets downloaded. It should be available afterwards that is to update audio-tags, when media download completes.

It would be nice feature to app, changing for audio-tags to all device media?

**Comment by Artx-II** [comment]
I had that idea in mind for some time and now that you mention it, yeah, it would be very useful.

I will implement it very soon.

**Comment by Artx-II** [comment]
This is now implemented, you can now change tags & artwork on any audio file shown in the app's Media (Downloads or Music)
