### ISSUE TITLE
YouTube Profile Pictures are bugged because they can be the same for diffrent channels

### ISSUE THREAD

**Issue by Z0pyrus** [SongTube/SongTube-App#163]
So, I've noticed that if the YouTube Channel Name is used several times, the profile Picture is staying the same for all of the channels with the same name.

That's because the AvatarHandler is petting the Profile Pictures in a directory of the channels name (instead of the url or something combined which is identifying someone definitely). So if there are 2 people with the same name, both will have the same profile picture. 

Avatar handler: SongTube-App\lib\internal\avatarHandler.dart

I wanted to commit it myself but I'm too stupid to get gradle to work.

**Comment by Artx-II** [comment]
Thank you for pointing this out, I will make the modifications necessary to fix this.

**Comment by Artx-II** [comment]
Fixed with commit #039a680
