### ISSUE TITLE
Refactoring filename as it gives error while importing 

### ISSUE THREAD

**Issue by bohrasankalp** [SongTube/SongTube-App#17]
2 files in ui folder - `FadeIn.dart` & `alertdialog.dart` should be in camelCase as it ends with import failure because of case sensitive imports.

Can we add `pedantic` or `effective_dart` for linting? It shows a lot of valid linting suggestions.

**Comment by Artx-II** [comment]
I believe everything is on camelCase now, if you find anything that isn't please open this issue again and I will fix it as soon as possible

And about linting packages, personally I do not want to bother with that, there are going to be tons of warnings and I honestly don't have the time to fix all of them. (That's my fault)

**Comment by sankalpbohra** [comment]
Please reopen the issue, Files I mentioned earlier still in the same case.

`/lib/ui/dialogs/alertdialog.dart` & `/lib/ui/animations/FadeIn.dart`
