### ISSUE TITLE
Download popup when pressed share

### ISSUE THREAD

**Issue by jsksek** [SongTube/SongTube-App#174]
The idea is that when you find a song you like on youtube you can just press share select songtube and the download popup will appear (kind of like in another app snaptube). This feature would make it super easy and quick to use. What you have to do now is click share once to open songtube and go back to yt, click share again it will open the video on songtube than u click download and finaly get to the popup. It takes quite some time.

**Comment by Artx-II** [comment]
Repository was updated with the new project. Opening the app on cold start using share with a youtube link should work now.
