### ISSUE TITLE
Playlist menu

### ISSUE THREAD

**Issue by heberjeur** [SongTube/SongTube-App#175]
Hi,

Can you please add the ability to show the playlists inside a YouTube channel ?

At the time being, when one opens a YouTube channel url ([example URL](https://www.youtube.com/channel/UCNb2H0PwlajFSmfjgfDdKvA/?disable_polymer=1)) on the smartphone and shares it to SongTube there is actually no way to show the playlists ([example playlists](https://www.youtube.com/channel/UCNb2H0PwlajFSmfjgfDdKvA/playlists?disable_polymer=1)) of that selected channel

SkyTube for example have this feature, I think is important to add to this application.

**Comment by Artx-II** [comment]
This is not possible with the current newpipe extractor library, so I'll be closing this.
