### ISSUE TITLE
it's-- very slow

### ISSUE THREAD

**Issue by ghost** [SongTube/SongTube-App#184]
Straightup takes like 30 seconds just to load one video. I have 1gbps internet speed

Is there a way to fix this? Like just speed it up a bit?

**Comment by ItzWarLockOp** [comment]
Me to Facing same issue. Other Things are Good Like Download speed and mp3 conversion. But The Main thing is slow.

https://user-images.githubusercontent.com/98949064/175802561-fe7733d1-b9b2-4c82-b5b8-b6ec5f2021bf.mp4

**Comment by Artx-II** [comment]
Repository was updated with the new project. Fixed by now.
