### ISSUE TITLE
Video will Not play and download Not start 

### ISSUE THREAD

**Issue by Pcf1337** [SongTube/SongTube-App#187]
The last 3 days the app is Not working anymore is there anyway to fix?

**Comment by GuikBretas** [comment]
Not working here too

**Comment by Beach77** [comment]
same forever loading

**Comment by CringyBoi42069** [comment]
Same here

**Comment by padiyes** [comment]
The same issue. Forever loading when trying to download or play any video online. Just able to play offline files.

**Comment by shockingfargroundx** [comment]
This sucks

**Comment by Beach77** [comment]
I have to ask. Has this app been abandoned?

**Comment by shockingfargroundx** [comment]
> I have to ask. Has this app been abandoned?

If feels like it. So far every update has the same fix applied saying it fixed videos not loading.

**Comment by Artx-II** [comment]
Issue is been fixed, new update coming soon

I've abandoned this project for a long time, but this will change on a big update pretty soon.

**Comment by shockingfargroundx** [comment]
> Issue is been fixed, new update coming soon
> 
> I've abandoned this project for a long time, but this will change on a big update pretty soon.

Thank you for not leaving it completely like everyone did on beat saber
