### ISSUE TITLE
Crashes when I play a video or download

### ISSUE THREAD

**Issue by 914th** [SongTube/SongTube-App#189]
when I first downloaded songtube it was working fine but after a few days it started crashing.

**Comment by Soulreaverbny** [comment]
I'm experiencing this too. I can navigate through the app and everything works fine until I try to play any video. When any video tries to play the apply completely shuts down.

**Comment by 4ph071c** [comment]
Having this issue as well.

**Comment by Artx-II** [comment]
Fixed

**Comment by Atheris142** [comment]
Hello, 

I have 6.4.5 version and got the same exact error. Installed the app, worked well a few days and stopped working (at first videos don't load and now directly crashes when I open a video). 

I don't know if this problem has reapeared.
