### ISSUE TITLE
Light Theme Bug

### ISSUE THREAD

**Issue by RickyM7** [SongTube/SongTube-App#19]
The three-dots menu of the videos is unreadable in the Light Theme. This does not occur in the Dark or Black Themes.
![IMG_20201211_061455](https://user-images.githubusercontent.com/24703825/101885077-631ea880-3b78-11eb-9e16-c2db389cbc9d.jpg)

App version: v5.1.0
Device: Redmi Note 4 (Miui 11 - Android 7.0)

**Comment by Clashkid155** [comment]
It's an already know bug (mentioned on tg).

**Comment by RickyM7** [comment]
@Clashkid155 Thanks for the info.

**Comment by Artx-II** [comment]
It's okay to have the issue open until the bug is fixed, that way someone else can try fix it or I can do it myselft when I get the time.

Anyways, this is a really easy fix so I will not re-open this because I already fixed it.
