### ISSUE TITLE
Migration to Flutter 3

### ISSUE THREAD

**Issue by bohrasankalp** [SongTube/SongTube-App#191]
Migrating to Flutter 3 makes a lot of deprication.

Flutter_slider is depricated.
Similarly, `Raised_Button` to `Elevated Button`.

I believe, in-build linter should be implemented to maintain consistency of code. There are few other package to automatically manage imports and reorganize it. Try to run `dart fix --dry-run`to get idea of what code be automatically get fixed by language itself. Clean cache and then rebuild.

**Comment by Artx-II** [comment]
Done.
