### ISSUE TITLE
videos no tocan

### ISSUE THREAD

**Issue by rlsgitmas** [SongTube/SongTube-App#194]
Los videos no tocan, nadamas aparecen en la pantalla pero no tocan. El círculo en la mitad de la pantalla está dando vueltas continuamente.

**Comment by lolpowerluke** [comment]
I have the same problem, is there any way to fix this?

**Comment by break999** [comment]
Same. Video is forever loading and never plays. Same with download option, forever loading.

**Comment by break999** [comment]
this is working: https://github.com/EarlGreytea16/SongTube-App/releases
