### ISSUE TITLE
SongTube crashing after loading any video

### ISSUE THREAD

**Issue by LenyLenard** [SongTube/SongTube-App#195]
### Steps to reproduce

First I open the app.
I click on any video (after searching or homepage) then it crashes after loading for around 2 seconds. 

### Expected behavior

Usually it never crashes it has always worked normally. 

### Actual behavior

SongTube just closes and sometimes I get a pop-up saying "SongTube has stopped" or something alike with an option to close the app 
Everything other feature apart from any included after clicking a video works fine.

### SongTube version

6.4.5

### Android version

Android 9

### Other details

I tried restarting my phone, uninstalled to reinstalled, then restarted. I deleted cache and user data too. Still have the same issue.
Out of nowhere it started doing this. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Updated repo with the new project. It works now.

A release will be made soon.
