### ISSUE TITLE
App isnt even workin

### ISSUE THREAD

**Issue by ITADORI-15** [SongTube/SongTube-App#197]

**Comment by EarlGreytea16** [comment]
This might work
https://github.com/EarlGreytea16/SongTube-App/releases/tag/2022-11-05-debug

**Comment by ITADORI-15** [comment]
![Screenshot_20221108-220906_SAI.jpg](https://user-images.githubusercontent.com/83289685/200623678-8298ac03-17de-4ec0-b3d4-9e1a6a9601f6.jpg)

**Comment by ITADORI-15** [comment]
![Screenshot_20221108-220855_SAI.jpg](https://user-images.githubusercontent.com/83289685/200623751-770281e0-d6cf-4be6-ab30-e3ceda375cd7.jpg)

**Comment by EarlGreytea16** [comment]
https://github.com/EarlGreytea16/SongTube-App/releases/tag/2022-11-05-debug
Try this, and what's your android's version?

**Comment by ITADORI-15** [comment]
Device samsung m 30
Android 10

**Comment by EarlGreytea16** [comment]
Did debug apk worked?

**Comment by ITADORI-15** [comment]
Yep....but my installer prevented me from installing saying there could be virus

**Comment by ITADORI-15** [comment]
Is it safe tho?

**Comment by ITADORI-15** [comment]
It did work thnx but

**Comment by EarlGreytea16** [comment]
It will be safe.
https://github.com/EarlGreytea16/SongTube-App/commit/cd61b509eea9b4c63004bd5fe8c02a833a856b4e

This is the commit about the app.

**Comment by ITADORI-15** [comment]
Thnx bruh

**Comment by Artx-II** [comment]
Updated repo with the new project. It works now.

A release will be made soon.

**Comment by EarlGreytea16** [comment]
Thanks! I was really waiting for the new version( ´ ▽ ` )ﾉ
