### ISSUE TITLE
Some strings that should be translatable

### ISSUE THREAD

**Issue by RickyM7** [SongTube/SongTube-App#20]
| "App" in App Personalization & Light/Dark|
| :---: |
| ![APP - Themes](https://user-images.githubusercontent.com/24703825/101889258-f9a19880-3b7d-11eb-9424-ce4e2d085497.jpg) |

| All in the Disclaimer message |
| :---: |
| ![Disclaimer](https://user-images.githubusercontent.com/24703825/101889759-8e0bfb00-3b7e-11eb-86fa-04c8a8cf33af.jpg) |

| Tags (Trending, Watch Later, etc) & Three-dots menu (of the videos) options |
| :---: |
| ![Tags - Three-dots menu](https://user-images.githubusercontent.com/24703825/101889852-a7ad4280-3b7e-11eb-87a1-424481469b88.jpg) |

| All in "Blur UI" option & "General" option title |
| :---: |
| ![Blur - General](https://user-images.githubusercontent.com/24703825/101890382-649f9f00-3b7f-11eb-8d76-9a166b33dc64.jpg) |

Note: If I find other strings that should be translatable I will update the issue.

**Comment by Artx-II** [comment]
All the missing translations are now implemented with commit f23f1cc. Please open a new pull request when you are done translating, thanks!

**Comment by RickyM7** [comment]
@Artx-II Thank you!
