### ISSUE TITLE
App crashes on launch 

### ISSUE THREAD

**Issue by owencz1998** [SongTube/SongTube-App#203]
### Steps to reproduce

Open app then instant crash and doesn't open 

### Expected behavior

Open app and work 

### Actual behavior

Just closes

### SongTube version

Latest

### Android version

Android 13

### Other details

Samsung z fold 3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
I am unable to reproduce this on different types of Android devices.

Did you compile the app yourself?

**Comment by owencz1998** [comment]
I literally just installed the app but does not launch on the Samsung z fold 3 android 13 at all I'll try different work arounds 1st

**Comment by owencz1998** [comment]
Can you maybe add actions to giyhub do I could test if the newer updated version would work (debug)

**Comment by Artx-II** [comment]
Since you closed this issue, I'm assuming you don't have this problem anymore, right?
