### ISSUE TITLE
Music Title 

### ISSUE THREAD

**Issue by MrConqueror** [SongTube/SongTube-App#204]
### Steps to reproduce

I changed or Put the full details of this song many times but it would still appear blank no matter what.

Some songs are Blank Edit Tags are Useless

### Expected behavior

.

### Actual behavior

.

### SongTube version

7.0.1

### Android version

Android 12

### Other details

![IMG_20230528_100821](https://github.com/SongTube/SongTube-App/assets/102837820/bb4ae131-7d6f-4815-b523-1e5e6294052b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Refer to issue #216 for tracking
