### ISSUE TITLE
Music tab never loads

### ISSUE THREAD

**Issue by MrBertie** [SongTube/SongTube-App#205]
### Steps to reproduce

Click on the Music tab at the bottom
It shows a loading splash screen with a spinner which says "Fetching songs, please wait a moment..."
I have waited 10-15 mins but it never loads

### Expected behavior

A list of trending or recent songs should display

### Actual behavior

Nothing happens

### SongTube version

7.0.1

### Android version

Android 13, Samsung A71, One UI 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Do you have a big music library in your phone?

I'm asking this because either it's taking abnormally long to load your music library (which is a bug) or somewhere in the loading process, there might be a song crashing the function in an unknown way.

In any case, I will check out this issue and try to reproduce it.

**Comment by MrBertie** [comment]
Yes I do have a big local music library. Can I prevent it from trying to index that?

**Comment by Artx-II** [comment]
Probably not, in this case I'm gonna have to refactor the songs fetch mechanism to make it faster,

**Comment by Artx-II** [comment]
I made an issue for this, refer to #207.

Once that issue is closed, it will mean that the problem have been solved, and its gonna come into the next Songtube update.
