### ISSUE TITLE
Delete Button & Rescan of Library

### ISSUE THREAD

**Issue by dazu89** [SongTube/SongTube-App#210]
### Describe your suggested feature

A delete button for a downloaded files would be nice, deleting files manually leaves an unassociated entry hence the idea of rescan the library to delete all relicts.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Sure, this can be done.

Thanks for the suggestion.

**Comment by Artx-II** [comment]
Done with commit [ed66656](https://github.com/SongTube/SongTube-App/commit/ed66656242391a0a1fa50ec2225453ea7747dd4f)
