### ISSUE TITLE
Remove useless button

### ISSUE THREAD

**Issue by Chen1Plus** [SongTube/SongTube-App#217]
### Steps to reproduce

1. Go to library
2. There is a list of songs, and each song has a three dots icon for option. Click it 
3. The option popup will be opened. Look at the right side of the title, another "option icon" exists. You can open unlimited popup pages. 

### Expected behavior

. 

### Actual behavior

. 

### SongTube version

7.0.1

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Fixed with commit 55d163e
