### ISSUE TITLE
Music downloaded to data folder instead of selected downloads folder

### ISSUE THREAD

**Issue by Quackdoc** [SongTube/SongTube-App#219]
### Steps to reproduce

1. create new folder (music/songtube)
2. point songtube to it
3. download file

### Expected behavior

song should show up in music/songtube/song.ogg

### Actual behavior

song shows up in android/data/com.artxdev.songtube/files/#####.ogg

### SongTube version

7.0.1

### Android version

Android 10

### Other details

haven't been able to test git since I dont have android sdk installed.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quackdoc** [comment]
for anyone else running into this issue, a temporary work around is to grant android.permission.WRITE_EXTERNAL_STORAGE no idea why it works. but it does. its an OK workaround

**Comment by Artx-II** [comment]
Upon checking with the information you provided, it seems like the permission you had to add manually is missing specifically on Android 10.

I've identified this problem and it's been fixed with commit 10fde9d

Thanks for bringing it out!

**Comment by AlexoMagno** [comment]
Hi, Can someone share the apk file from this commit [10fde9d](https://github.com/SongTube/SongTube-App/commit/10fde9d3026f83df863503f145e80a4dddff6cf5) ?

**Comment by Artx-II** [comment]
> Hi, Can someone share the apk file from this commit [10fde9d](https://github.com/SongTube/SongTube-App/commit/10fde9d3026f83df863503f145e80a4dddff6cf5) ?

Latest release has this change. Check https://github.com/SongTube/SongTube-App/releases for APK's
