### ISSUE TITLE
Music Title could not be edited 

### ISSUE THREAD

**Issue by MrConqueror** [SongTube/SongTube-App#220]
### Steps to reproduce

I have this Song downloaded already and I edit tags it in S0ngtube but no matter how many i do it the outcome is always like this. basically edit tags doesn't work on this app. I really thought you've been reading our report within the app but you weren't. The issue is not yet solved, i was expecting it's fixed since there was a new version or update, i wish you resolve this. 

![Screenshot_2023-07-03-08-08-00-817_com artxdev songtube-edit](https://github.com/SongTube/SongTube-App/assets/102837820/03383e13-c7b4-45cf-945d-4823d974d072)

### Expected behavior

.

### Actual behavior

.

### SongTube version

7.1.0+2000

### Android version

Android 13

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Refer to issue #216 for tracking
