### ISSUE TITLE
Delete Music

### ISSUE THREAD

**Issue by MrConqueror** [SongTube/SongTube-App#223]
### Describe your suggested feature

Change to three dots from equalizer, and when we tap the three dots it shows the edit tags, add to Playlist delete song etc. i downloaded this song from this app and i was trying to delete it because there's i accidentally downloaded it three times and i couldn't find the delete option.

### Other details

![IMG_20230719_195943](https://github.com/SongTube/SongTube-App/assets/102837820/d2bfd03c-fa25-4110-829b-cf87c50028fc)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Feature added with commit 069cbc4
