### ISSUE TITLE
Add ability to force use of video or audio mode while streaming

### ISSUE THREAD

**Issue by The-Ducktor** [SongTube/SongTube-App#224]
### Describe your suggested feature

Add the ability as a button on the video to allow the user to change the way the YouTube video or music is being played instead of just being able to do so while downloading one

### Other details
Prehaps it could be placed like this
![Screenshot_20230804-212021](https://github.com/SongTube/SongTube-App/assets/130664593/6db87646-2242-4ebd-8f04-d9f28a72915f)

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Implemented with commit 5ce4724
