### ISSUE TITLE
Option to have a default filter

### ISSUE THREAD

**Issue by shivanshvermak** [SongTube/SongTube-App#229]
### Describe your suggested feature

Since this app is used as a music app, it's helpful to keep the "Music Songs" filter as active all the time. If possible, please add this feature. 

Thank you for this amazing app!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Sure, I will add an option to make filters persistent for the next update.

**Comment by Artx-II** [comment]
This feature is now available since 6810131
