### ISSUE TITLE
Shuffle on downloads show wrong thumbnail and title

### ISSUE THREAD

**Issue by phoenix3605** [SongTube/SongTube-App#231]
### Steps to reproduce

Shuffle on downloads

### Expected behavior

Shows correct thumbnail and title with matching audio

### Actual behavior

Audio plays with different thumbnail and title

### SongTube version

7.1.2+3000

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
I can confirm the issue, not only in downloads but everywhere. This will be fixed for the next update.

**Comment by Artx-II** [comment]
Fixed with commit 878c746
