### ISSUE TITLE
[REQUEST]accessibility with screen readers

### ISSUE THREAD

**Issue by MesterPerfect** [SongTube/SongTube-App#233]
### Describe your suggested feature

Good morning
I am a blind user
There are a lot of buttons that I can't name using a talkback screen reader
Can you apply the accessibility guidelines provided by the flutter team here to improve accessibility?
https://docs.flutter.dev/ui/accessibility-and-localization/accessibility

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Done with commit #4899478
