### ISSUE TITLE
Video Not Playing

### ISSUE THREAD

**Issue by mohitdebian** [SongTube/SongTube-App#234]
### Steps to reproduce

In SongTube when i play any YouTube video it's only loading not playing. Whenever I play any video it stuck on loading loop it never plays. Please tell me if this issue is fixed then what should I do because it's not working. Tell me what steps I have to take to solve this issue when I compile

### Expected behavior

It should play video not have to stuck on continuous loop

### Actual behavior

But when i play any YouTube video it's only loading not playing. Whenever I play any video it stuck on loading loop it never plays. Please tell me if this issue is fixed then what should I do because it's not working. Tell me what steps I have to take to solve this issue when I compile

### SongTube version

7.1.2+3000

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Are you sure you're on the latest 7.1.2 update?

You can also try restarting your phone, this have solved the issue in those extremely rare cases where the video would not load.

**Comment by Artx-II** [comment]
Closing this issue since there is no reply.
