### ISSUE TITLE
an idea for the future of the app on windows and a feature

### ISSUE THREAD

**Issue by BlackSleepYT** [SongTube/SongTube-App#242]
### Describe your suggested feature

In spanish but you can use google translate
la idea seria hacer que tambien se pueda instalar en pc windows o linux creo que se podria si esta hecho como creo que lo esta y hacer un binario para windows seria bueno ya que tambien atraeria a personas de windows y otra mas seria la de añadir una lista de reproduccion predeterminada que seria la de ver mas tarde y serie increible o al menos poder hacer que en favoritos puedas cambiar el orden del mas antiguo primero al mas reciente primero no se si me hago entender.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Hacer un binario para Windows no es posible, esta app utiliza librerias nativas que solo funcionan en Android y no pueden compilar para Windows.
