### ISSUE TITLE
app creates a playlist rather letting us read comments.

### ISSUE THREAD

**Issue by idontveapc** [SongTube/SongTube-App#247]
### Steps to reproduce

1. play a video on the homepage
2. see comments window
3. tap the window
4. empty
5. press back arrow
6. a playlist is showed and comments window disappeared.

### Expected behavior

"comments should load and a playlist(s) control option must be added"

### Actual behavior

"the comments load empty"

### SongTube version

latest(sep8)

### Android version

android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Cannot replicate this issue, I'll close this but if it comes up again in the next update please re-open this again and I'll have a look.
