### ISSUE TITLE
Download button hard to find

### ISSUE THREAD

**Issue by Esokrates** [SongTube/SongTube-App#249]
### Describe your suggested feature

The default position of the "Download" button is not ideal, one has to navigate to the right in order to see it. In the beginning it took a long time to discover it and other users I recommended to app also keep complaining that the download button is hard to discover.
The "Popup Mode" button is the last button that is shown by default, "Download" is hidden right next to it. I propose you exchange the position of those two buttons. Furthermore, the "Popup Mode" button does nothing for me, clicking it, does not do anything.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ishanvaghani** [comment]
@Artx-II Can we put the download button in the third or fourth position? This can fix the issue because not many users use popup mode. If yes, then I will do that.

**Comment by Artx-II** [comment]
Download button is now at the third position with commit 530f773
