### ISSUE TITLE
[FR] Create Music Playlist File with Segmented Download  - easier to import into music players

### ISSUE THREAD

**Issue by rlsgitmas** [SongTube/SongTube-App#252]
### Describe your suggested feature

Segmented Download should create a Playlist File that can be easily imported along with segmented files into other music players.

Currently the Playlist is connected to SongTube app, but it woud be more user friendly if the segmented files along with its Playlist file could be imported into other music players. 

Thanks for all your efforts on this project.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Not exactly sure how does other music players support import of playlists or what the standard is if there is any.

Will close this for the meanwhile, unless I am missing something or not understanding the issue please open this again.

**Comment by rlsgitmas** [comment]
I haven't figure out how the **Create a Playlist File**  checkbox option works, I have a few questions:

1. Is the Playlist File meant to work inside SongTube only?  
2. Does  the checkbox create a file? and if so, 
3. Where is the Playlist File located?

Note: If I download a segmented audio inside a folder, SongTube plays the correct order of songs, however if I import the folder into AIMP player (or any other player) the order of songs is not correct 

![segmentd downloads](https://github.com/SongTube/SongTube-App/assets/92409568/400bfafa-c59a-4d1f-9c43-f51c012050c1)
