### ISSUE TITLE
[FR] Swipe and Double Tap on Artwork to control Music Player (similar to AIMP)

### ISSUE THREAD

**Issue by rlsgitmas** [SongTube/SongTube-App#253]
### Describe your suggested feature

A Swipe on Artwork should change to next (or previous) track when using Music Player. Also, Double Tap on bottom right of artwork should fast forward the current playing song 10 seconds, and vice versa for Double tap on bottom left. 

The artwork is the largest part of the UI in the Music Player and the easiest to access to quickly change music, so the Swipe and Double Tap gestures will greatly improve the user experience

The suggested Swipe and Double Tap gestures are currently implemented in the following three Android Music players. 

AIMP: http://www.aimp.ru/ (swipe album art to change tracks and double touch on lower corners of album art to fast forward or fast backward)
Vinyl Music player : https://github.com/VinylMusicPlayer/VinylMusicPlayer (swipe album art to change tracks only)
Retro Music player: https://github.com/RetroMusicPlayer/RetroMusicPlayer (swipe album art to change tracks only)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ishanvaghani** [comment]
Hey @rlsgitmas can you share the video here for both the features if possible?

**Comment by rlsgitmas** [comment]
The attached video shows the following gestures(in AIMP): 
1) Fast forward by double touch on lower right of album art
2) Change tracks by swiping on album art.
https://github.com/SongTube/SongTube-App/assets/92409568/8f6496ed-37de-40f3-ad04-7e4d6710e274

**Comment by Artx-II** [comment]
Implemented with commit 6f2bb47

Thanks to @ishanvaghani !
