### ISSUE TITLE
Cannot delete or modify Music Playlist of .m4a files created with Segmented Downloads [Music Player]

### ISSUE THREAD

**Issue by rlsgitmas** [SongTube/SongTube-App#254]
### Steps to reproduce

1. Download a Segmented download of songs.
2. Open the playlist in Music Player (Music note icon on SongTube app)
3. Click on downloaded playlist

Downloaded playlist cannot be deleted or modified

Issue with not been able to delete playlist: When files are deleted from the device, the playlist still shows in the Music Player.
Issue with not been able to not modify playlist: If user does not want some of the songs on the list there is no option to remove them

### Expected behavior

1. Download a Segmented download of songs.
2. Open the playlist in Music Player (Music note icon on SongTube app)
3. Click on downloaded playlist
Option to delete playlist should appear when holding playlist icon (or there is an option to delete the playlist when inside the playlist.

When inside the playlist there should be an option to hold the track name and remove it from the playlist

### Actual behavior

1. Download a Segmented download of songs.
2. Open the playlist in Music Player (Music note icon on SongTube app)
3. Click on downloaded playlist

Downloaded playlist cannot be deleted or modified

### SongTube version

7.2.0

### Android version

7.2.p

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
A series of commits have been pushed to fix the missing parts

978c6dd Adds a button on the Playlist Screen to delete the playlist
6fe35b3 Adds a gesture on the playlist song tiles, swiping left reveals a delete button which removes that song from the playlist
ff1acee Changes the caption on the song options sheet to make it clear you can add/remove that song from any playlist
