### ISSUE TITLE
Play/Resume Button for Notification Panel

### ISSUE THREAD

**Issue by deans-bradley** [SongTube/SongTube-App#258]
### Steps to reproduce

**Play/Resume button for notification panel not resuming audio.** 

1. Open SongTube.
2. Play song from the music screen. 
3. Open notification panel.
4. Press pause button in music player in the notification panel, then press play/resume.

**Player in notification panel. Song playing.**
![notification player play](https://i.imgur.com/QKacNfL.jpg)

### Expected behavior

Song should continue playing.

### Actual behavior

Song remains paused. Pause/Resume/Play button does not change states. 

**Player in notification panel. Song paused.**
![notification player paused](https://i.imgur.com/K7PbwNH.jpg)

### SongTube version

7.2.0

### Android version

14

### Other details

**Device:** Galaxy S21 5G
**One UI version:** 6.0
**File type of song:** .mp3

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the latest version **[Latest](https://github.com/SongTube/SongTube-App/releases)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Artx-II** [comment]
Fixed with 2e6cd32
