### ISSUE TITLE
Others strings that should be translatable

### ISSUE THREAD

**Issue by RickyM7** [SongTube/SongTube-App#26]
- Allow Access:
![permission](https://user-images.githubusercontent.com/24703825/103241620-885e3580-4932-11eb-99ca-5bb4503fe5d6.jpg)

- Link copied to Clipboard (3-dots video menu>Copy Link):
![clipboard](https://user-images.githubusercontent.com/24703825/103241787-0a4e5e80-4933-11eb-8893-15a30b93acfe.jpg)

-  Loading…(3-dots video menu>Download):
![loading download](https://user-images.githubusercontent.com/24703825/103241911-51d4ea80-4933-11eb-9889-13f0b2e14add.jpg)

- Video added to Favorites(3-dots video menu>Add to Favorites):
![added to favorites](https://user-images.githubusercontent.com/24703825/103241952-729d4000-4933-11eb-8fad-7139fb48ee64.jpg)

- Video removed from Favorites:
![removed favorites](https://user-images.githubusercontent.com/24703825/103241986-8ba5f100-4933-11eb-8a5c-d94ee14df6fa.jpg)

- Video add to Watch Later(3-dots video menu>Add to Watch Later):
![added to watch later](https://user-images.githubusercontent.com/24703825/103242051-c4de6100-4933-11eb-8544-956ddbf70cbd.jpg)

- Video removed from Watch Later:
![removed watch later](https://user-images.githubusercontent.com/24703825/103242083-dc1d4e80-4933-11eb-8185-e60db3e89721.jpg)

- Default (in converter settings>gain controls>volume):
![default volume](https://user-images.githubusercontent.com/24703825/103242167-11c23780-4934-11eb-83da-f42836a2f7f7.jpg)

**Comment by Artx-II** [comment]
Are we still missing translations?

**Comment by RickyM7** [comment]
> Are we still missing translations?

I have to test the latest version to see this and tell you, but the app is crashing (as reported in #50), so I can't see that at the moment.

**Comment by Artx-II** [comment]
This issue is very old and I completely lost track of the required translations, please open a new issue with the specific translations to be worked on, thanks!
