### ISSUE TITLE
Implement opt-in or out app updates

### ISSUE THREAD

**Issue by Artx-II** [SongTube/SongTube-App#263]
### Describe your suggested feature

SongTube performs an update check in the background every time the app is opened, but a one-time dialog to let the user choose to opt-in or out from the updates check mechanism would be a more reasonable implementation that would meet F-Droid's inclusion criteria.

The app should also clarify in this dialog and the settings menu, from where is the information extracted and APK downloaded from.

This a follow up from issue #262. @IzzySoft Let me know if I missed something, thanks!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ishanvaghani** [comment]
I can work on this

**Comment by Artx-II** [comment]
Done with commit 372cb4d
