### ISSUE TITLE
[Feature Request] Normalize audio

### ISSUE THREAD

**Issue by RickyM7** [SongTube/SongTube-App#29]
I do not know if this is possible (that's ok if it is not), but it would be amazing to have an option to normalize the audio before downloading.

### Links that can be useful
https://github.com/peterforgacs/ffmpeg-normalize

https://github.com/slhck/ffmpeg-normalize

**Comment by Clashkid155** [comment]
Should be possible since ffmpeg is being used.

**Comment by Artx-II** [comment]
Sure, I'll add an audio normalization option to the filters.

**Comment by RickyM7** [comment]
@Artx-II Thank you so much!

**Comment by Artx-II** [comment]
This feature is now implemented with commit 61dda2c!
