### ISSUE TITLE
[Enhancement] Re-work downloads screen and save a downloads history

### ISSUE THREAD

**Issue by Artx-II** [SongTube/SongTube-App#30]
It would be very helpful to have nicer looking Downloads screen with more details of each download and a downloads history

**Comment by Clashkid155** [comment]
Would you save them in pref

**Comment by Artx-II** [comment]
yeah shared preferences would be the easiest

**Comment by Artx-II** [comment]
Moved downloads from Media Screen to Download Screen (these downloads are pulled from local database, you can considerate it like a download history) on commit ef630fb
