### ISSUE TITLE
[Bug] AutoPlay always active

### ISSUE THREAD

**Issue by RickyM7** [SongTube/SongTube-App#36]
Turning off AutoPlay does not work, videos always start automatically regardless of whether the "AutoPlay" option is on or off.

- Device: Redmi Note 4 (MIUI 11 - Android 7.0)
- App version: v5.3.0+6

**Comment by Artx-II** [comment]
Thanks for reporting! I will check and fix it.

**Comment by Artx-II** [comment]
Fixed!
