### ISSUE TITLE
Please add content location option

### ISSUE THREAD

**Issue by brnwlshubh** [SongTube/SongTube-App#41]
Content of particular country is unique.
And there should be option to change the country and also the media content.

**Comment by Artx-II** [comment]
Content location is not available because I am not actually getting Youtube's Feed but just some playlists, I will implement this once a proper youtube feed extractor is implemented.

**Comment by Artx-II** [comment]
Re-opening this because now content location is possible!

**Comment by Artx-II** [comment]
Now by default, the extractor fetch content from your default location
