### ISSUE TITLE
Getting error while run 

### ISSUE THREAD

**Issue by ermkmandawar** [SongTube/SongTube-App#45]
please guide me how can I solve these errors. I'm new in flutter.
It's my log
`Launching lib\main.dart on IN2021 in debug mode...`
`Running Gradle task 'assembleDebug'...`
`lib/internal/ffmpeg/converter.dart:42:65: Error: The operator '[]' isn't defined for the class 'MediaInformation'.`
 `- 'MediaInformation' is from 'package:flutter_ffmpeg/media_information.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.1/lib/media_information.dart').
Try correcting the operator to an existing operator, or defining a '[]' operator.
    return (await flutterFFprobe.getMediaInformation(mediaFile))["duration"];
                                                                ^
lib/internal/ffmpeg/extractor.dart:234:16: Error: The operator '[]' isn't defined for the class 'MediaInformation'.`
` - 'MediaInformation' is from 'package:flutter_ffmpeg/media_information.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.1/lib/media_information.dart').
Try correcting the operator to an existing operator, or defining a '[]' operator.
    return json['duration'];
               ^
lib/internal/ffmpeg/extractor.dart:240:19: Error: The operator '[]' isn't defined for the class 'MediaInformation'.`
` - 'MediaInformation' is from 'package:flutter_ffmpeg/media_information.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.1/lib/media_information.dart').
Try correcting the operator to an existing operator, or defining a '[]' operator.
    return "${json["metadata"]["date"]}";
                  ^
lib/internal/ffmpeg/extractor.dart:246:19: Error: The operator '[]' isn't defined for the class 'MediaInformation'.`
` - 'MediaInformation' is from 'package:flutter_ffmpeg/media_information.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.1/lib/media_information.dart').
Try correcting the operator to an existing operator, or defining a '[]' operator.
    return "${json["metadata"]["disc"]}";
                  ^
lib/internal/ffmpeg/extractor.dart:252:19: Error: The operator '[]' isn't defined for the class 'MediaInformation'.`
` - 'MediaInformation' is from 'package:flutter_ffmpeg/media_information.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ffmpeg-0.3.1/lib/media_information.dart').
Try correcting the operator to an existing operator, or defining a '[]' operator.
    return "${json["metadata"]["track"]}";
                  ^
lib/players/service/playerService.dart:291:28: Error: Getter not found: 'none'.
      case ProcessingState.none:
                           ^^^^`

**Comment by Artx-II** [comment]
I've updated the pubspec.yaml with all the packages up to date. Please try again and if it works you can close the issue 👍
