### ISSUE TITLE
[Feature Request] ability to download at custom start/end

### ISSUE THREAD

**Issue by pervertkirito** [SongTube/SongTube-App#5]
set to download only on certain point of the video.

using YouTube url ` ?start=X&end=X ` for example.

or implement something like [Sponsor Block](https://github.com/ajayyy/SponsorBlock)

**Comment by Artx-II** [comment]
This is way too complicated and I don't have time for that, if someone else wants to add this feature feel free to open this issue again until it's done.

What might be possible is to cut the video from specific start to specific end after it's downloaded, if that would still help you, please open this issue again and label it as "Enhancement", thanks!
