### ISSUE TITLE
Crash while opening the app

### ISSUE THREAD

**Issue by RickyM7** [SongTube/SongTube-App#50]
The app is closing right after opening and this only occurs after you complete the initial setup.

- Device: Redmi Note 4 (MIUI 11 - Android 7.0)
- App version: v6.0.0+80 (GitHub)

**Comment by Artx-II** [comment]
Some people are experiencing the same, can you somehow extract and show me the crash log? Meanwhile I will try out some things, build a test apk and upload it for people with this issue to test in the telegram group.

**Comment by RickyM7** [comment]
> ...can you somehow extract and show me the crash log?

Unfortunately not, I'm sorry.

**Comment by Artx-II** [comment]
No problem, I will try reverting some commits and adjusting some values, can you test once it's done?

**Comment by RickyM7** [comment]
> No problem, I will try reverting some commits and adjusting some values, can you test once it's done?

Yes, of course.

**Comment by RickyM7** [comment]
@Artx-II I just tested the v6.2.0 and the crash no longer occurs. Thank you!
