### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by SanOtaku09** [SongTube/SongTube-App#51]
Add a option in setting to switch between video & audio only for YouTube music and use music player for listening to that audio
So songtube can be used as online music player
Many of us just wanna listen to audio and don't care about video so it will be a very useful and will save allot of data
One app already had done this :-  ymusic 
Here's the app link if u wanna see the app (ymusic.io) 
So I don't think it's impossible to do
I hope u will add this feature
Thank you for your awesome app

**Comment by Artx-II** [comment]
Sounds like a really nice idea, I'm working on implementing Picture in Picture and background playback, once that is done I will work on your feature request, thanks 👍

**Comment by Artx-II** [comment]
This is done
