### ISSUE TITLE
Few Enhancements

### ISSUE THREAD

**Issue by bohrasankalp** [SongTube/SongTube-App#55]
I found few enhancements which were working prior to version v.6 but that's not working now. 
1. If I search for some artist/song or anything (eg. Mozart), so next time song tube app on bootstrapping automatically suggests for `Mozart` keyword. This time, no matter how much time I search, it loads abrupt suggestions on all the time.
2. Suggestion list is repeating same suggestion, pagination might not working.
3. While playing video, if I tap (left/right) it works and moves the video to and fro but the same doesn't work if I try to tap the player navigator and move forward.

**Comment by bohrasankalp** [comment]
Issues/Enhancement:

1. Sharing playlist doesn't launch the app. In case if the app is running in the background, it only takes that playlist.
2. It never asks in which format the playlist needs to be download. Though it prompted for 3 options, audio, video, and download playlist all, it downloads playlist in audio format only.
  * It automatically to audio format, No options to download playlist as videos.
  * There should be an option to choose video playlists' type, format, & quality if I wish to download the whole playlist.
  * The user should be notified if he chooses any of the 3 options to download and `bottom sheet` would disappear automatically.
3. Whole the playlist is getting duplicates in the download section. Queued videos are duplicates in the playlist. Could be the reason I clicked download playlist multiple times.
4. It should avoid downloading the same video(with the exact same quality) if an already downloaded version is available. 
5. More options to choose the location, by prompting default location on the drive.
5. Moreover, clearing the queue, along with the feature to hard delete with content on disk.

**Comment by bohrasankalp** [comment]
Again with a new suggestion.
1. What about `voice search`?

**Comment by bohrasankalp** [comment]
- Video and list from media section never calculate time. Its always shows calculating. Same for audio as well, it should display time.
- app crashes few time when scrolling video media list

**Comment by Artx-II** [comment]
Will open a new issue for the last two issues, closing this.
