### ISSUE TITLE
[Enhacement] Migration to flutter 2

### ISSUE THREAD

**Issue by bohrasankalp** [SongTube/SongTube-App#56]
I upgraded to flutter 2 and it all failed :). Any plans for migration?

**Comment by Clashkid155** [comment]
Works for me on F2

**Comment by bohrasankalp** [comment]
`Sliding_up_panel`, `Circular_checkbox` am9ng few failing for me.

**Comment by Artx-II** [comment]
Those two packages have been completely removed, try build development branch, should now work without issues

**Comment by bohrasankalp** [comment]
@Artx-II I am enhancing my skills with your code. Create some WhatsApp, Slack channels where we could connect.

**Comment by Artx-II** [comment]
Glad to hear that, you can contact me via email or telegram @artx4dev. If the app now builds without issues feel free to close this issue 👍🏼
