### ISSUE TITLE
Audio Segmentation Bug

### ISSUE THREAD

**Issue by mubashir-rehman** [SongTube/SongTube-App#63]
When segmentation is applied on long videos like(https://www.youtube.com/watch?v=xyOLf0j_40o). The process continues but gets stuck at converting. I will add the image and sample video in next comment. Logs are sent in pm on telegram to Artx from @mubashirrehman .
Edit: Video file is also sent on telegram in pm to Artx because video size exceeds the github file limit.

**Comment by mubashir-rehman** [comment]
![image](https://user-images.githubusercontent.com/51048830/118518976-1efc8900-b752-11eb-8c4b-d69c51a79e39.png)

**Comment by Artx-II** [comment]
I tried to download the same video with segmentation enabled and everything else on default, it worked fine, for me it seems that you had a setting in the audio download menu by default that was triggering FFmpeg.

Anyways, this file is way too large for FFmpeg to process it on a mobile environment, so, I'll make some adjustments to make sure conversion is disabled for large audio files.

**Comment by Artx-II** [comment]
Will open a new issue for this to keep track of what I actually have to do
