### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by harshmandan** [SongTube/SongTube-App#67]
Please update the old dependencies to newer versions. It compiles with so many warnings!

If you want I can submit a PR?

**Comment by Artx-II** [comment]
Sure! You can request a review from me and once I get some time available I will test and merge it.

Thank you

**Comment by harshmandan** [comment]
@Artx-II can you please accept the PR in the extractor repo first. Thanks!

**Comment by harshmandan** [comment]
@Artx-II https://github.com/SongTube/SongTube-App/pull/68 Done!

**Comment by Artx-II** [comment]
I'll merge it soon, sorry if it's taking too long my time is currently extremely constrained

**Comment by Artx-II** [comment]
Done!
