### ISSUE TITLE
Compilation Issue and Outdated Libraries and Android V2 Compatibility

### ISSUE THREAD

**Issue by VstMusic-SoloStudio** [SongTube/SongTube-App#78]
There are crashes in the application, I cannot recompile.  It gives an error because the libraries used are out of date.  The comments section is not visible.  Some songs and videos do not play.  Download speed slowed down.  It doesn't find all the songs or videos.  Homepage content must be country specific.

**Comment by Artx-II** [comment]
All build issues have been sorted out, please try again, closing this issue also because homepage country specific content has already an issue on the board.
