### ISSUE TITLE
[Home Page] UI improvement (Tabs)

### ISSUE THREAD

**Issue by vedxp** [SongTube/SongTube-App#84]
![IMG_20210929_133212_200](https://user-images.githubusercontent.com/87353286/135227846-07fb7fab-4137-447c-b411-2dda6a42e0d1.jpg)

The text **Watch Later** gets hidden.

It should either fit in the screen or make the tabs text area swipable, so that swiping text area; all tabs' name is there!

**Comment by Artx-II** [comment]
Making the panel swipable would leave an undesirable look to users with larger screen sizes, this should come in once the home page have more tabs

**Comment by AnonyUnknownTg** [comment]
> Making the panel swipable would leave an undesirable look to users with larger screen sizes, this should come in once the home page have more tabs

But still, in smaller devices; the text shouldn't be hidden.

Have to do something to fit the text within the screen for all screen sizes.
