### ISSUE TITLE
[Video Player] UX improvement (Hide Controls)

### ISSUE THREAD

**Issue by VedxP** [SongTube/SongTube-App#85]
![IMG_20210929_134017](https://user-images.githubusercontent.com/87353286/135229064-86f3dfaf-8fe2-4761-847a-3ab11343233c.jpg)

Auto hide controls feature, like the original YT and NewPipe app.

Currently, it needs additional tap to hide the controls.

**Comment by Artx-II** [comment]
Auto-hide should work fine, can you share the steps to reproduce the bug?

**Comment by AnonyUnknownTg** [comment]
> Auto-hide should work fine, can you share the steps to reproduce the bug?

Ahh, it's not a bug; just add auto-hide controls after a defined period, like 3 seconds.
