### ISSUE TITLE
[Channel] Extractor update required (Uploads Feed)

### ISSUE THREAD

**Issue by vedxp** [SongTube/SongTube-App#87]
![IMG_20210929_134637_720](https://user-images.githubusercontent.com/87353286/135230112-98660b54-29b0-4ede-a0d0-8d7a3e01bafc.jpg)

Can't swipe more than this, means it loads only few videos.

This issue was seen in the old versions of NewPipe, but they've fixed it!

**Comment by Artx-II** [comment]
Repository was updated with the new project. Fixed by now.
