### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by AnonyUnknownTg** [SongTube/SongTube-App#88]
![IMG_20210929_134902_278](https://user-images.githubusercontent.com/87353286/135230440-98dcd245-821e-4576-a34c-372237bd91ec.jpg)

This area is fixed at top, consuming much space while swiping through videos.

Rather, it should minimize as it does on video details/playing page.

**Comment by Artx-II** [comment]
More than half the screen on this is dedicated to show uploaded videos, I don't think we need this because this page is not yet loaded with widgets and advanced features.

**Comment by AnonyUnknownTg** [comment]
![Screenshot_20210929-192745_SongTube](https://user-images.githubusercontent.com/87353286/135283220-8c53b4bc-cb43-4d44-a260-36896db91d98.png)

I was talking about this; like on video page, swiping down beautifully minimizes the channel info tab.

The same for channel page won't be bad though!

**Comment by AnonyUnknownTg** [comment]
@Artx-II 
Consider above comment!
