### ISSUE TITLE
[Feature Request] Convert/Download in Wav format

### ISSUE THREAD

**Issue by RickyM7** [SongTube/SongTube-App#9]
It would be great if it were possible to convert/download audios in .wav with the highest possible quality.

**Comment by Artx-II** [comment]
There is no such format in youtube videos, but I can add support to convert to .wav

**Comment by RickyM7** [comment]
@Artx-II That would be great, thank you.

**Comment by Artx-II** [comment]
Implemented with commit a24aafd

Took 3 years, I forgot about this one, sorry haha 😅
