### ISSUE TITLE
[Video Player] UX improvement (Icon gets stuck)

### ISSUE THREAD

**Issue by AnonyUnknownTg** [SongTube/SongTube-App#95]
https://user-images.githubusercontent.com/87353286/135288265-59661fb3-b7e7-4e8c-a520-40acb2faf9f2.mp4

Steps to reproduce:

_Play any video
Tap on share
The video pauses
Cancel share
The video is still paused
Check the icon_

Instead, when sharing the video, if the video is to be paused; it should show the icon to pause the video, but currently, it gets stuck assumimg the video is playing.

**Comment by Artx-II** [comment]
Solved
