### ISSUE TITLE
[Channel Page] Channel icon doesn't load

### ISSUE THREAD

**Issue by AnonyUnknownTg** [SongTube/SongTube-App#96]
![IMG_20210930_173010_429](https://user-images.githubusercontent.com/87353286/135451330-6d0f0038-fcfa-480f-90c3-eeb39bcda0d9.jpg)

**Comment by Clashkid155** [comment]
Does this happen with all channels?

**Comment by AnonyUnknownTg** [comment]
> Does this happen with all channels?

For me, yes; but only on Channel Page.

**Comment by Artx-II** [comment]
This shouldn't happen anymore
