### ISSUE TITLE
[Popup Player] Icon stuck issue (As seen in #95)

### ISSUE THREAD

**Issue by AnonyUnknownTg** [SongTube/SongTube-App#97]
![IMG_20210930_173227_151](https://user-images.githubusercontent.com/87353286/135451709-98761717-d539-4207-9ef3-cc7c0f17eba4.jpg)

The video is playing, but icon got stuck!

**Comment by Artx-II** [comment]
Currently not possible to fix since support for PiP is very limited on Flutter
