### ISSUE TITLE
[Video Player] UI bug (Scales video to vertical fullscreen player)

### ISSUE THREAD

**Issue by vedxp** [SongTube/SongTube-App#98]
![IMG_20210930_173703_073](https://user-images.githubusercontent.com/87353286/135452218-1b5952c2-b2e6-4ed4-bcd1-e20aa22d2a6f.jpg)
![IMG_20210930_173704_958](https://user-images.githubusercontent.com/87353286/135452255-742e07ee-a029-4270-830d-66d69122708a.jpg)

Additional information:
OS: MIUI Global 12.5.2
Device: Redmi Note 10

I've another device from Realme, running Android 11; which doesn't seem to produce same glitch.

**Comment by Artx-II** [comment]
This happens when the device supports PiP mode and automatic PiP is enabled, definitely a bug
