### ISSUE TITLE
[Comments] Comments Count (Show total number of comments in video details page)

### ISSUE THREAD

**Issue by vedxp** [SongTube/SongTube-App#99]
![IMG_20210930_174144_074](https://user-images.githubusercontent.com/87353286/135452881-b16818b8-2b03-43cb-a0a2-156d99d02532.jpg)

**Comment by Artx-II** [comment]
Repository was updated with the new project.

The comments extracted are limited, and there is currently no pagination or plans to implement that, so, showing total number of comments would be a bit misleading because in most cases we can't show all of them.
